name: DCO Check

on: 
  pull_request:

jobs:
  dco_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Get PR Commits
      id: commits
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.commits.outputs.commits }}
