name: Check __init__.py Modified

on:
  push:
    branches: [master]

jobs:
  check-init:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
      - name: Determine if __init__.py modified
        id: modified
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${changed_file} == "chaostoolkit/__init__.py" ]];
            then
              echo "::set-output name=MODIFIED::TRUE"; # __init__.py was modified
              exit 0
            fi
          done
          echo "::set-output name=MODIFIED::FALSE" # __init__.py was not modified
          exit 0
      - name: Check Modified
        if: ${{ steps.modified.outputs.MODIFIED == 'FALSE' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('__init__.py was not modified')