name: Check __init__.py Modified

on:
  push:
    branches: [master]

jobs:
  check-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        uses: tj-actions/changed-files@v1.1.2
        id: files
      - name: Determine if __init__.py modified
        id: modified
        run: |
          init_modified=false
          changelog_modified=false
          for changed_file in ${{ steps.files.outputs.all_modified_files }}; do
            if [[ ${changed_file} == "chaostoolkit/__init__.py" ]];
            then
              init_modified=true # __init__.py was modified
            elif [[ ${changed_file} == "CHANGELOG.md" ]];
            then
              changelog_modified=true # CHANGELOG.md was modified
            fi
          done
          if [[ ${init_modified} == false ]];
          then
            echo "__init__.py was not modified"
          fi
          if [[ ${changelog_modified} == false ]];
          then
            echo "CHANGELOG.md was not modified"
          fi
          if [[ ${init_modified} == false || ${changelog_modified} == false ]];
          then
            exit 1
          fi
          exit 0