name: Initiate Timeboxed Issue

on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Label
        id: check-label
        # if [[ ${{ github.event.label.name }} =~ ^[1|2]?[0-9]days$ ]];
        run: |
          if [[ ${{ github.event.label.name }} =~ days$ ]];
          then
            echo "::set-output name=TIMEBOXLABEL::TRUE";
            exit 0
          fi
          echo "::set-output name=TIMEBOXLABEL::FALSE";
          exit 0
      - name: Create Comment
        if: ${{ steps.check-label.outputs.TIMEBOXLABEL == 'TRUE' }}
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "${{ github.event.label.name }} Added"
          issue_number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}